name: flutter_map
description: A versatile mapping package for Flutter, based off leaflet.js,
  that's simple and easy to learn, yet completely customizable and configurable.
version: 3.1.0
repository: https://github.com/fleaflet/flutter_map
issue_tracker: https://github.com/fleaflet/flutter_map/issues
documentation: https://docs.fleaflet.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  latlong2: ^0.9.1
  meta: ^1.11.0
  polylabel: ^1.0.1
  proj4dart: ^2.1.0
  tuple: ^2.0.0
  vector_math: ^2.1.2
  positioned_tap_detector_2:
    git:
      url: https://github.com/AndreiMisiukevich/flutter-positioned-tap-detector.git
